version: "3.5"

networks:
    webnet:
        name: default-docker-apps-network
        external: true

services:
    sample-mysql-server:
        image: mysql-server:latest
        deploy:
            replicas: 1
            resources:
                limits:
                    cpus: "0.1"
                    memory: 50M
            restart_policy:
                condition: on-failure
        environment:
            - MYSQL_ROOT_PASSWORD=root_pass
            - MYSQL_DATABASE=sample_database
            - MYSQL_USER=user
            - MYSQL_PASSWORD=pass
        networks:
            - webnet
